linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - unused
    - misspell

linters-settings:
  errcheck:
    check-blank: false
  misspell:
    ignore-words:
      - routeros

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 5

run:
  timeout: 5m
  tests: true
