// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: stormd.proto

package stormdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadListRequest) Reset() {
	*x = WorkloadListRequest{}
	mi := &file_stormd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadListRequest) ProtoMessage() {}

func (x *WorkloadListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadListRequest.ProtoReflect.Descriptor instead.
func (*WorkloadListRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{0}
}

type WorkloadListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*WorkloadInfo        `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadListResponse) Reset() {
	*x = WorkloadListResponse{}
	mi := &file_stormd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadListResponse) ProtoMessage() {}

func (x *WorkloadListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadListResponse.ProtoReflect.Descriptor instead.
func (*WorkloadListResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadListResponse) GetWorkloads() []*WorkloadInfo {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type WorkloadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`     // "container" or "vm"
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "stopped", "failed", "restarting"
	Pid           uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	RestartCount  uint32                 `protobuf:"varint,5,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	ContainerId   string                 `protobuf:"bytes,6,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,7,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	PodIp         string                 `protobuf:"bytes,8,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	NodeId        string                 `protobuf:"bytes,9,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadInfo) Reset() {
	*x = WorkloadInfo{}
	mi := &file_stormd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadInfo) ProtoMessage() {}

func (x *WorkloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadInfo.ProtoReflect.Descriptor instead.
func (*WorkloadInfo) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkloadInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkloadInfo) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *WorkloadInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WorkloadInfo) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *WorkloadInfo) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *WorkloadInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type WorkloadActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadActionRequest) Reset() {
	*x = WorkloadActionRequest{}
	mi := &file_stormd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadActionRequest) ProtoMessage() {}

func (x *WorkloadActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadActionRequest.ProtoReflect.Descriptor instead.
func (*WorkloadActionRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{3}
}

func (x *WorkloadActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadActionResponse) Reset() {
	*x = WorkloadActionResponse{}
	mi := &file_stormd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadActionResponse) ProtoMessage() {}

func (x *WorkloadActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadActionResponse.ProtoReflect.Descriptor instead.
func (*WorkloadActionResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkloadActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WorkloadCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "container" or "vm"
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,4,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"` // "always", "on-failure", "never"
	CpuLimit      string                 `protobuf:"bytes,5,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,6,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	Command       []string               `protobuf:"bytes,7,rep,name=command,proto3" json:"command,omitempty"`
	Env           []string               `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty"`
	Ports         []*PortMapping         `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes       []*VolumeMount         `protobuf:"bytes,10,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCreateRequest) Reset() {
	*x = WorkloadCreateRequest{}
	mi := &file_stormd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCreateRequest) ProtoMessage() {}

func (x *WorkloadCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCreateRequest.ProtoReflect.Descriptor instead.
func (*WorkloadCreateRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadCreateRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadCreateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *WorkloadCreateRequest) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *WorkloadCreateRequest) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *WorkloadCreateRequest) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *WorkloadCreateRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WorkloadCreateRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *WorkloadCreateRequest) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *WorkloadCreateRequest) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      uint32                 `protobuf:"varint,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort uint32                 `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp" or "udp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_stormd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{6}
}

func (x *PortMapping) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_stormd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VolumeMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VolumeMount) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type WorkloadLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          uint32                 `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadLogsRequest) Reset() {
	*x = WorkloadLogsRequest{}
	mi := &file_stormd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadLogsRequest) ProtoMessage() {}

func (x *WorkloadLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadLogsRequest.ProtoReflect.Descriptor instead.
func (*WorkloadLogsRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{8}
}

func (x *WorkloadLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *WorkloadLogsRequest) GetTail() uint32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_stormd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_stormd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{10}
}

type NodeStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	UptimeSecs      uint64                 `protobuf:"varint,2,opt,name=uptime_secs,json=uptimeSecs,proto3" json:"uptime_secs,omitempty"`
	WorkloadCount   uint32                 `protobuf:"varint,3,opt,name=workload_count,json=workloadCount,proto3" json:"workload_count,omitempty"`
	RunningCount    uint32                 `protobuf:"varint,4,opt,name=running_count,json=runningCount,proto3" json:"running_count,omitempty"`
	MemoryTotal     uint64                 `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryAvailable uint64                 `protobuf:"varint,6,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	DiskTotal       uint64                 `protobuf:"varint,7,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskAvailable   uint64                 `protobuf:"varint,8,opt,name=disk_available,json=diskAvailable,proto3" json:"disk_available,omitempty"`
	CpuInfo         []string               `protobuf:"bytes,9,rep,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`
	NodeId          string                 `protobuf:"bytes,10,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PodCidr         string                 `protobuf:"bytes,11,opt,name=pod_cidr,json=podCidr,proto3" json:"pod_cidr,omitempty"`
	MeshPeers       uint32                 `protobuf:"varint,12,opt,name=mesh_peers,json=meshPeers,proto3" json:"mesh_peers,omitempty"`
	Cordoned        bool                   `protobuf:"varint,13,opt,name=cordoned,proto3" json:"cordoned,omitempty"`
	CordonReason    string                 `protobuf:"bytes,14,opt,name=cordon_reason,json=cordonReason,proto3" json:"cordon_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_stormd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{11}
}

func (x *NodeStatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeStatusResponse) GetUptimeSecs() uint64 {
	if x != nil {
		return x.UptimeSecs
	}
	return 0
}

func (x *NodeStatusResponse) GetWorkloadCount() uint32 {
	if x != nil {
		return x.WorkloadCount
	}
	return 0
}

func (x *NodeStatusResponse) GetRunningCount() uint32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

func (x *NodeStatusResponse) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *NodeStatusResponse) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *NodeStatusResponse) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *NodeStatusResponse) GetDiskAvailable() uint64 {
	if x != nil {
		return x.DiskAvailable
	}
	return 0
}

func (x *NodeStatusResponse) GetCpuInfo() []string {
	if x != nil {
		return x.CpuInfo
	}
	return nil
}

func (x *NodeStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatusResponse) GetPodCidr() string {
	if x != nil {
		return x.PodCidr
	}
	return ""
}

func (x *NodeStatusResponse) GetMeshPeers() uint32 {
	if x != nil {
		return x.MeshPeers
	}
	return 0
}

func (x *NodeStatusResponse) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

func (x *NodeStatusResponse) GetCordonReason() string {
	if x != nil {
		return x.CordonReason
	}
	return ""
}

type ImagePullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePullRequest) Reset() {
	*x = ImagePullRequest{}
	mi := &file_stormd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePullRequest) ProtoMessage() {}

func (x *ImagePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePullRequest.ProtoReflect.Descriptor instead.
func (*ImagePullRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{12}
}

func (x *ImagePullRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type ImagePullResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ManifestDigest string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImagePullResponse) Reset() {
	*x = ImagePullResponse{}
	mi := &file_stormd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePullResponse) ProtoMessage() {}

func (x *ImagePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePullResponse.ProtoReflect.Descriptor instead.
func (*ImagePullResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{13}
}

func (x *ImagePullResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImagePullResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImagePullResponse) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

type ImageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListRequest) Reset() {
	*x = ImageListRequest{}
	mi := &file_stormd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListRequest) ProtoMessage() {}

func (x *ImageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListRequest.ProtoReflect.Descriptor instead.
func (*ImageListRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{14}
}

type ImageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []string               `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListResponse) Reset() {
	*x = ImageListResponse{}
	mi := &file_stormd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListResponse) ProtoMessage() {}

func (x *ImageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListResponse.ProtoReflect.Descriptor instead.
func (*ImageListResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{15}
}

func (x *ImageListResponse) GetDigests() []string {
	if x != nil {
		return x.Digests
	}
	return nil
}

type ImageEnsureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"` // image reference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageEnsureRequest) Reset() {
	*x = ImageEnsureRequest{}
	mi := &file_stormd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageEnsureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEnsureRequest) ProtoMessage() {}

func (x *ImageEnsureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEnsureRequest.ProtoReflect.Descriptor instead.
func (*ImageEnsureRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{16}
}

func (x *ImageEnsureRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type ImageEnsureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Available      bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ManifestDigest string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageEnsureResponse) Reset() {
	*x = ImageEnsureResponse{}
	mi := &file_stormd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageEnsureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEnsureResponse) ProtoMessage() {}

func (x *ImageEnsureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEnsureResponse.ProtoReflect.Descriptor instead.
func (*ImageEnsureResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{17}
}

func (x *ImageEnsureResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ImageEnsureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImageEnsureResponse) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

type NodeDrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graceful      bool                   `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"`                 // true = wait for workloads to stop, false = force
	TimeoutS      uint32                 `protobuf:"varint,2,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"` // max seconds to wait (0 = default 300s)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDrainRequest) Reset() {
	*x = NodeDrainRequest{}
	mi := &file_stormd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDrainRequest) ProtoMessage() {}

func (x *NodeDrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDrainRequest.ProtoReflect.Descriptor instead.
func (*NodeDrainRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{18}
}

func (x *NodeDrainRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

func (x *NodeDrainRequest) GetTimeoutS() uint32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

type NodeDrainResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WorkloadsStopped uint32                 `protobuf:"varint,3,opt,name=workloads_stopped,json=workloadsStopped,proto3" json:"workloads_stopped,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeDrainResponse) Reset() {
	*x = NodeDrainResponse{}
	mi := &file_stormd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDrainResponse) ProtoMessage() {}

func (x *NodeDrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDrainResponse.ProtoReflect.Descriptor instead.
func (*NodeDrainResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{19}
}

func (x *NodeDrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeDrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeDrainResponse) GetWorkloadsStopped() uint32 {
	if x != nil {
		return x.WorkloadsStopped
	}
	return 0
}

type NodeCordonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // e.g. "os-update", "maintenance"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCordonRequest) Reset() {
	*x = NodeCordonRequest{}
	mi := &file_stormd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCordonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCordonRequest) ProtoMessage() {}

func (x *NodeCordonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCordonRequest.ProtoReflect.Descriptor instead.
func (*NodeCordonRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{20}
}

func (x *NodeCordonRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NodeCordonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cordoned      bool                   `protobuf:"varint,3,opt,name=cordoned,proto3" json:"cordoned,omitempty"` // resulting cordon state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCordonResponse) Reset() {
	*x = NodeCordonResponse{}
	mi := &file_stormd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCordonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCordonResponse) ProtoMessage() {}

func (x *NodeCordonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCordonResponse.ProtoReflect.Descriptor instead.
func (*NodeCordonResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{21}
}

func (x *NodeCordonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NodeCordonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeCordonResponse) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

type MeshUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*MeshNode            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshUpdateRequest) Reset() {
	*x = MeshUpdateRequest{}
	mi := &file_stormd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshUpdateRequest) ProtoMessage() {}

func (x *MeshUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshUpdateRequest.ProtoReflect.Descriptor instead.
func (*MeshUpdateRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{22}
}

func (x *MeshUpdateRequest) GetNodes() []*MeshNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MeshNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // "ip:port" for WireGuard
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	TunnelIp      string                 `protobuf:"bytes,5,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`
	PodCidr       string                 `protobuf:"bytes,6,opt,name=pod_cidr,json=podCidr,proto3" json:"pod_cidr,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"` // "controller", "worker", "controller+worker"
	Healthy       bool                   `protobuf:"varint,8,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshNode) Reset() {
	*x = MeshNode{}
	mi := &file_stormd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNode) ProtoMessage() {}

func (x *MeshNode) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNode.ProtoReflect.Descriptor instead.
func (*MeshNode) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{23}
}

func (x *MeshNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MeshNode) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MeshNode) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MeshNode) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MeshNode) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *MeshNode) GetPodCidr() string {
	if x != nil {
		return x.PodCidr
	}
	return ""
}

func (x *MeshNode) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MeshNode) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type MeshUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActivePeers   uint32                 `protobuf:"varint,2,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshUpdateResponse) Reset() {
	*x = MeshUpdateResponse{}
	mi := &file_stormd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshUpdateResponse) ProtoMessage() {}

func (x *MeshUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshUpdateResponse.ProtoReflect.Descriptor instead.
func (*MeshUpdateResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{24}
}

func (x *MeshUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MeshUpdateResponse) GetActivePeers() uint32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

type ServiceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceEntry        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdateRequest) Reset() {
	*x = ServiceUpdateRequest{}
	mi := &file_stormd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdateRequest) ProtoMessage() {}

func (x *ServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{25}
}

func (x *ServiceUpdateRequest) GetServices() []*ServiceEntry {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints     []*ServiceEndpointMsg  `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_stormd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{26}
}

func (x *ServiceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceEntry) GetEndpoints() []*ServiceEndpointMsg {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ServiceEndpointMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpointMsg) Reset() {
	*x = ServiceEndpointMsg{}
	mi := &file_stormd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpointMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpointMsg) ProtoMessage() {}

func (x *ServiceEndpointMsg) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpointMsg.ProtoReflect.Descriptor instead.
func (*ServiceEndpointMsg) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{27}
}

func (x *ServiceEndpointMsg) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ServiceEndpointMsg) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceEndpointMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServiceEndpointMsg) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ServiceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServicesCount uint32                 `protobuf:"varint,2,opt,name=services_count,json=servicesCount,proto3" json:"services_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdateResponse) Reset() {
	*x = ServiceUpdateResponse{}
	mi := &file_stormd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdateResponse) ProtoMessage() {}

func (x *ServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{28}
}

func (x *ServiceUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceUpdateResponse) GetServicesCount() uint32 {
	if x != nil {
		return x.ServicesCount
	}
	return 0
}

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_stormd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{29}
}

type ClusterStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeCount        uint32                 `protobuf:"varint,1,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	HealthyNodes     uint32                 `protobuf:"varint,2,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	TotalWorkloads   uint32                 `protobuf:"varint,3,opt,name=total_workloads,json=totalWorkloads,proto3" json:"total_workloads,omitempty"`
	RunningWorkloads uint32                 `protobuf:"varint,4,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`
	Nodes            []*MeshNode            `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_stormd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{30}
}

func (x *ClusterStatusResponse) GetNodeCount() uint32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *ClusterStatusResponse) GetHealthyNodes() uint32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *ClusterStatusResponse) GetTotalWorkloads() uint32 {
	if x != nil {
		return x.TotalWorkloads
	}
	return 0
}

func (x *ClusterStatusResponse) GetRunningWorkloads() uint32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *ClusterStatusResponse) GetNodes() []*MeshNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type WorkloadCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // workload name to checkpoint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCheckpointRequest) Reset() {
	*x = WorkloadCheckpointRequest{}
	mi := &file_stormd_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCheckpointRequest) ProtoMessage() {}

func (x *WorkloadCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCheckpointRequest.ProtoReflect.Descriptor instead.
func (*WorkloadCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{31}
}

func (x *WorkloadCheckpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadCheckpointResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CheckpointPath string                 `protobuf:"bytes,3,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"` // path to checkpoint directory
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadCheckpointResponse) Reset() {
	*x = WorkloadCheckpointResponse{}
	mi := &file_stormd_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCheckpointResponse) ProtoMessage() {}

func (x *WorkloadCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCheckpointResponse.ProtoReflect.Descriptor instead.
func (*WorkloadCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{32}
}

func (x *WorkloadCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkloadCheckpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadCheckpointResponse) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

type WorkloadRestoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CheckpointPath string                 `protobuf:"bytes,1,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"` // path to checkpoint directory or archive
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadRestoreRequest) Reset() {
	*x = WorkloadRestoreRequest{}
	mi := &file_stormd_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRestoreRequest) ProtoMessage() {}

func (x *WorkloadRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRestoreRequest.ProtoReflect.Descriptor instead.
func (*WorkloadRestoreRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{33}
}

func (x *WorkloadRestoreRequest) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

type WorkloadRestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,3,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"` // name of restored workload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRestoreResponse) Reset() {
	*x = WorkloadRestoreResponse{}
	mi := &file_stormd_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRestoreResponse) ProtoMessage() {}

func (x *WorkloadRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRestoreResponse.ProtoReflect.Descriptor instead.
func (*WorkloadRestoreResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{34}
}

func (x *WorkloadRestoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkloadRestoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadRestoreResponse) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

type VmMigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadName  string                 `protobuf:"bytes,1,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"` // VM workload to migrate
	DestUrl       string                 `protobuf:"bytes,2,opt,name=dest_url,json=destUrl,proto3" json:"dest_url,omitempty"`                // destination receiver URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmMigrateRequest) Reset() {
	*x = VmMigrateRequest{}
	mi := &file_stormd_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmMigrateRequest) ProtoMessage() {}

func (x *VmMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmMigrateRequest.ProtoReflect.Descriptor instead.
func (*VmMigrateRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{35}
}

func (x *VmMigrateRequest) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *VmMigrateRequest) GetDestUrl() string {
	if x != nil {
		return x.DestUrl
	}
	return ""
}

type VmMigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmMigrateResponse) Reset() {
	*x = VmMigrateResponse{}
	mi := &file_stormd_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmMigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmMigrateResponse) ProtoMessage() {}

func (x *VmMigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmMigrateResponse.ProtoReflect.Descriptor instead.
func (*VmMigrateResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{36}
}

func (x *VmMigrateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VmMigrateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VmSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadName  string                 `protobuf:"bytes,1,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	DestPath      string                 `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"` // directory to store snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmSnapshotRequest) Reset() {
	*x = VmSnapshotRequest{}
	mi := &file_stormd_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSnapshotRequest) ProtoMessage() {}

func (x *VmSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSnapshotRequest.ProtoReflect.Descriptor instead.
func (*VmSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{37}
}

func (x *VmSnapshotRequest) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *VmSnapshotRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

type VmSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SnapshotPath  string                 `protobuf:"bytes,3,opt,name=snapshot_path,json=snapshotPath,proto3" json:"snapshot_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmSnapshotResponse) Reset() {
	*x = VmSnapshotResponse{}
	mi := &file_stormd_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSnapshotResponse) ProtoMessage() {}

func (x *VmSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSnapshotResponse.ProtoReflect.Descriptor instead.
func (*VmSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{38}
}

func (x *VmSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VmSnapshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VmSnapshotResponse) GetSnapshotPath() string {
	if x != nil {
		return x.SnapshotPath
	}
	return ""
}

type NetworkPolicy struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pod selector (label-based, simplified to name prefix)
	PodSelector   string               `protobuf:"bytes,3,opt,name=pod_selector,json=podSelector,proto3" json:"pod_selector,omitempty"`
	IngressRules  []*NetworkPolicyRule `protobuf:"bytes,4,rep,name=ingress_rules,json=ingressRules,proto3" json:"ingress_rules,omitempty"`
	EgressRules   []*NetworkPolicyRule `protobuf:"bytes,5,rep,name=egress_rules,json=egressRules,proto3" json:"egress_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_stormd_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{39}
}

func (x *NetworkPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkPolicy) GetPodSelector() string {
	if x != nil {
		return x.PodSelector
	}
	return ""
}

func (x *NetworkPolicy) GetIngressRules() []*NetworkPolicyRule {
	if x != nil {
		return x.IngressRules
	}
	return nil
}

func (x *NetworkPolicy) GetEgressRules() []*NetworkPolicyRule {
	if x != nil {
		return x.EgressRules
	}
	return nil
}

type NetworkPolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []uint32               `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"` // allowed ports (empty = all)
	Cidrs         []string               `protobuf:"bytes,2,rep,name=cidrs,proto3" json:"cidrs,omitempty"`         // allowed CIDRs (e.g. "10.42.0.0/16")
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`   // "tcp", "udp", or "" for any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_stormd_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{40}
}

func (x *NetworkPolicyRule) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NetworkPolicyRule) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

func (x *NetworkPolicyRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type NetworkPolicyApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *NetworkPolicy         `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyApplyRequest) Reset() {
	*x = NetworkPolicyApplyRequest{}
	mi := &file_stormd_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyApplyRequest) ProtoMessage() {}

func (x *NetworkPolicyApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyApplyRequest.ProtoReflect.Descriptor instead.
func (*NetworkPolicyApplyRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{41}
}

func (x *NetworkPolicyApplyRequest) GetPolicy() *NetworkPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type NetworkPolicyApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RulesApplied  uint32                 `protobuf:"varint,3,opt,name=rules_applied,json=rulesApplied,proto3" json:"rules_applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyApplyResponse) Reset() {
	*x = NetworkPolicyApplyResponse{}
	mi := &file_stormd_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyApplyResponse) ProtoMessage() {}

func (x *NetworkPolicyApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyApplyResponse.ProtoReflect.Descriptor instead.
func (*NetworkPolicyApplyResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{42}
}

func (x *NetworkPolicyApplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NetworkPolicyApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NetworkPolicyApplyResponse) GetRulesApplied() uint32 {
	if x != nil {
		return x.RulesApplied
	}
	return 0
}

type NetworkPolicyDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyDeleteRequest) Reset() {
	*x = NetworkPolicyDeleteRequest{}
	mi := &file_stormd_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyDeleteRequest) ProtoMessage() {}

func (x *NetworkPolicyDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyDeleteRequest.ProtoReflect.Descriptor instead.
func (*NetworkPolicyDeleteRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{43}
}

func (x *NetworkPolicyDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyDeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NetworkPolicyDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RulesRemoved  uint32                 `protobuf:"varint,3,opt,name=rules_removed,json=rulesRemoved,proto3" json:"rules_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyDeleteResponse) Reset() {
	*x = NetworkPolicyDeleteResponse{}
	mi := &file_stormd_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyDeleteResponse) ProtoMessage() {}

func (x *NetworkPolicyDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyDeleteResponse.ProtoReflect.Descriptor instead.
func (*NetworkPolicyDeleteResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{44}
}

func (x *NetworkPolicyDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NetworkPolicyDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NetworkPolicyDeleteResponse) GetRulesRemoved() uint32 {
	if x != nil {
		return x.RulesRemoved
	}
	return 0
}

type NetworkPolicyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // empty = all namespaces
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyListRequest) Reset() {
	*x = NetworkPolicyListRequest{}
	mi := &file_stormd_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyListRequest) ProtoMessage() {}

func (x *NetworkPolicyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyListRequest.ProtoReflect.Descriptor instead.
func (*NetworkPolicyListRequest) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{45}
}

func (x *NetworkPolicyListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NetworkPolicyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*NetworkPolicy       `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyListResponse) Reset() {
	*x = NetworkPolicyListResponse{}
	mi := &file_stormd_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyListResponse) ProtoMessage() {}

func (x *NetworkPolicyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stormd_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyListResponse.ProtoReflect.Descriptor instead.
func (*NetworkPolicyListResponse) Descriptor() ([]byte, []int) {
	return file_stormd_proto_rawDescGZIP(), []int{46}
}

func (x *NetworkPolicyListResponse) GetPolicies() []*NetworkPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_stormd_proto protoreflect.FileDescriptor

const file_stormd_proto_rawDesc = "" +
	"\n" +
	"\fstormd.proto\x12\x06stormd\"\x15\n" +
	"\x13WorkloadListRequest\"J\n" +
	"\x14WorkloadListResponse\x122\n" +
	"\tworkloads\x18\x01 \x03(\v2\x14.stormd.WorkloadInfoR\tworkloads\"\xff\x01\n" +
	"\fWorkloadInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12#\n" +
	"\rrestart_count\x18\x05 \x01(\rR\frestartCount\x12!\n" +
	"\fcontainer_id\x18\x06 \x01(\tR\vcontainerId\x12%\n" +
	"\x0erestart_policy\x18\a \x01(\tR\rrestartPolicy\x12\x15\n" +
	"\x06pod_ip\x18\b \x01(\tR\x05podIp\x12\x17\n" +
	"\anode_id\x18\t \x01(\tR\x06nodeId\"+\n" +
	"\x15WorkloadActionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x16WorkloadActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc2\x02\n" +
	"\x15WorkloadCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12%\n" +
	"\x0erestart_policy\x18\x04 \x01(\tR\rrestartPolicy\x12\x1b\n" +
	"\tcpu_limit\x18\x05 \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x06 \x01(\tR\vmemoryLimit\x12\x18\n" +
	"\acommand\x18\a \x03(\tR\acommand\x12\x10\n" +
	"\x03env\x18\b \x03(\tR\x03env\x12)\n" +
	"\x05ports\x18\t \x03(\v2\x13.stormd.PortMappingR\x05ports\x12-\n" +
	"\avolumes\x18\n" +
	" \x03(\v2\x13.stormd.VolumeMountR\avolumes\"m\n" +
	"\vPortMapping\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\rR\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\rR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"Y\n" +
	"\vVolumeMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\"U\n" +
	"\x13WorkloadLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\rR\x04tail\"Z\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11NodeStatusRequest\"\xe0\x03\n" +
	"\x12NodeStatusResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vuptime_secs\x18\x02 \x01(\x04R\n" +
	"uptimeSecs\x12%\n" +
	"\x0eworkload_count\x18\x03 \x01(\rR\rworkloadCount\x12#\n" +
	"\rrunning_count\x18\x04 \x01(\rR\frunningCount\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x04R\vmemoryTotal\x12)\n" +
	"\x10memory_available\x18\x06 \x01(\x04R\x0fmemoryAvailable\x12\x1d\n" +
	"\n" +
	"disk_total\x18\a \x01(\x04R\tdiskTotal\x12%\n" +
	"\x0edisk_available\x18\b \x01(\x04R\rdiskAvailable\x12\x19\n" +
	"\bcpu_info\x18\t \x03(\tR\acpuInfo\x12\x17\n" +
	"\anode_id\x18\n" +
	" \x01(\tR\x06nodeId\x12\x19\n" +
	"\bpod_cidr\x18\v \x01(\tR\apodCidr\x12\x1d\n" +
	"\n" +
	"mesh_peers\x18\f \x01(\rR\tmeshPeers\x12\x1a\n" +
	"\bcordoned\x18\r \x01(\bR\bcordoned\x12#\n" +
	"\rcordon_reason\x18\x0e \x01(\tR\fcordonReason\"0\n" +
	"\x10ImagePullRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"p\n" +
	"\x11ImagePullResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\"\x12\n" +
	"\x10ImageListRequest\"-\n" +
	"\x11ImageListResponse\x12\x18\n" +
	"\adigests\x18\x01 \x03(\tR\adigests\"2\n" +
	"\x12ImageEnsureRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"v\n" +
	"\x13ImageEnsureResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\"K\n" +
	"\x10NodeDrainRequest\x12\x1a\n" +
	"\bgraceful\x18\x01 \x01(\bR\bgraceful\x12\x1b\n" +
	"\ttimeout_s\x18\x02 \x01(\rR\btimeoutS\"t\n" +
	"\x11NodeDrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11workloads_stopped\x18\x03 \x01(\rR\x10workloadsStopped\"+\n" +
	"\x11NodeCordonRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"d\n" +
	"\x12NodeCordonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bcordoned\x18\x03 \x01(\bR\bcordoned\";\n" +
	"\x11MeshUpdateRequest\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.stormd.MeshNodeR\x05nodes\"\xe0\x01\n" +
	"\bMeshNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1b\n" +
	"\ttunnel_ip\x18\x05 \x01(\tR\btunnelIp\x12\x19\n" +
	"\bpod_cidr\x18\x06 \x01(\tR\apodCidr\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x18\n" +
	"\ahealthy\x18\b \x01(\bR\ahealthy\"Q\n" +
	"\x12MeshUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\factive_peers\x18\x02 \x01(\rR\vactivePeers\"H\n" +
	"\x14ServiceUpdateRequest\x120\n" +
	"\bservices\x18\x01 \x03(\v2\x14.stormd.ServiceEntryR\bservices\"\\\n" +
	"\fServiceEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\tendpoints\x18\x02 \x03(\v2\x1a.stormd.ServiceEndpointMsgR\tendpoints\"k\n" +
	"\x12ServiceEndpointMsg\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\"X\n" +
	"\x15ServiceUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eservices_count\x18\x02 \x01(\rR\rservicesCount\"\x16\n" +
	"\x14ClusterStatusRequest\"\xd9\x01\n" +
	"\x15ClusterStatusResponse\x12\x1d\n" +
	"\n" +
	"node_count\x18\x01 \x01(\rR\tnodeCount\x12#\n" +
	"\rhealthy_nodes\x18\x02 \x01(\rR\fhealthyNodes\x12'\n" +
	"\x0ftotal_workloads\x18\x03 \x01(\rR\x0etotalWorkloads\x12+\n" +
	"\x11running_workloads\x18\x04 \x01(\rR\x10runningWorkloads\x12&\n" +
	"\x05nodes\x18\x05 \x03(\v2\x10.stormd.MeshNodeR\x05nodes\"/\n" +
	"\x19WorkloadCheckpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"y\n" +
	"\x1aWorkloadCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fcheckpoint_path\x18\x03 \x01(\tR\x0echeckpointPath\"A\n" +
	"\x16WorkloadRestoreRequest\x12'\n" +
	"\x0fcheckpoint_path\x18\x01 \x01(\tR\x0echeckpointPath\"r\n" +
	"\x17WorkloadRestoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rworkload_name\x18\x03 \x01(\tR\fworkloadName\"R\n" +
	"\x10VmMigrateRequest\x12#\n" +
	"\rworkload_name\x18\x01 \x01(\tR\fworkloadName\x12\x19\n" +
	"\bdest_url\x18\x02 \x01(\tR\adestUrl\"G\n" +
	"\x11VmMigrateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x11VmSnapshotRequest\x12#\n" +
	"\rworkload_name\x18\x01 \x01(\tR\fworkloadName\x12\x1b\n" +
	"\tdest_path\x18\x02 \x01(\tR\bdestPath\"m\n" +
	"\x12VmSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsnapshot_path\x18\x03 \x01(\tR\fsnapshotPath\"\xe2\x01\n" +
	"\rNetworkPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fpod_selector\x18\x03 \x01(\tR\vpodSelector\x12>\n" +
	"\ringress_rules\x18\x04 \x03(\v2\x19.stormd.NetworkPolicyRuleR\fingressRules\x12<\n" +
	"\fegress_rules\x18\x05 \x03(\v2\x19.stormd.NetworkPolicyRuleR\vegressRules\"[\n" +
	"\x11NetworkPolicyRule\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\rR\x05ports\x12\x14\n" +
	"\x05cidrs\x18\x02 \x03(\tR\x05cidrs\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"J\n" +
	"\x19NetworkPolicyApplyRequest\x12-\n" +
	"\x06policy\x18\x01 \x01(\v2\x15.stormd.NetworkPolicyR\x06policy\"u\n" +
	"\x1aNetworkPolicyApplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rrules_applied\x18\x03 \x01(\rR\frulesApplied\"N\n" +
	"\x1aNetworkPolicyDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"v\n" +
	"\x1bNetworkPolicyDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rrules_removed\x18\x03 \x01(\rR\frulesRemoved\"8\n" +
	"\x18NetworkPolicyListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"N\n" +
	"\x19NetworkPolicyListResponse\x121\n" +
	"\bpolicies\x18\x01 \x03(\v2\x15.stormd.NetworkPolicyR\bpolicies2\xe9\r\n" +
	"\vStormDaemon\x12I\n" +
	"\fWorkloadList\x12\x1b.stormd.WorkloadListRequest\x1a\x1c.stormd.WorkloadListResponse\x12N\n" +
	"\rWorkloadStart\x12\x1d.stormd.WorkloadActionRequest\x1a\x1e.stormd.WorkloadActionResponse\x12M\n" +
	"\fWorkloadStop\x12\x1d.stormd.WorkloadActionRequest\x1a\x1e.stormd.WorkloadActionResponse\x12O\n" +
	"\x0eWorkloadRemove\x12\x1d.stormd.WorkloadActionRequest\x1a\x1e.stormd.WorkloadActionResponse\x12?\n" +
	"\fWorkloadLogs\x12\x1b.stormd.WorkloadLogsRequest\x1a\x10.stormd.LogEntry0\x01\x12C\n" +
	"\n" +
	"NodeStatus\x12\x19.stormd.NodeStatusRequest\x1a\x1a.stormd.NodeStatusResponse\x12@\n" +
	"\tImagePull\x12\x18.stormd.ImagePullRequest\x1a\x19.stormd.ImagePullResponse\x12@\n" +
	"\tImageList\x12\x18.stormd.ImageListRequest\x1a\x19.stormd.ImageListResponse\x12O\n" +
	"\x0eWorkloadCreate\x12\x1d.stormd.WorkloadCreateRequest\x1a\x1e.stormd.WorkloadActionResponse\x12@\n" +
	"\tNodeDrain\x12\x18.stormd.NodeDrainRequest\x1a\x19.stormd.NodeDrainResponse\x12C\n" +
	"\n" +
	"NodeCordon\x12\x19.stormd.NodeCordonRequest\x1a\x1a.stormd.NodeCordonResponse\x12E\n" +
	"\fNodeUncordon\x12\x19.stormd.NodeCordonRequest\x1a\x1a.stormd.NodeCordonResponse\x12F\n" +
	"\vImageEnsure\x12\x1a.stormd.ImageEnsureRequest\x1a\x1b.stormd.ImageEnsureResponse\x12C\n" +
	"\n" +
	"MeshUpdate\x12\x19.stormd.MeshUpdateRequest\x1a\x1a.stormd.MeshUpdateResponse\x12L\n" +
	"\rServiceUpdate\x12\x1c.stormd.ServiceUpdateRequest\x1a\x1d.stormd.ServiceUpdateResponse\x12L\n" +
	"\rClusterStatus\x12\x1c.stormd.ClusterStatusRequest\x1a\x1d.stormd.ClusterStatusResponse\x12[\n" +
	"\x12NetworkPolicyApply\x12!.stormd.NetworkPolicyApplyRequest\x1a\".stormd.NetworkPolicyApplyResponse\x12^\n" +
	"\x13NetworkPolicyDelete\x12\".stormd.NetworkPolicyDeleteRequest\x1a#.stormd.NetworkPolicyDeleteResponse\x12X\n" +
	"\x11NetworkPolicyList\x12 .stormd.NetworkPolicyListRequest\x1a!.stormd.NetworkPolicyListResponse\x12[\n" +
	"\x12WorkloadCheckpoint\x12!.stormd.WorkloadCheckpointRequest\x1a\".stormd.WorkloadCheckpointResponse\x12R\n" +
	"\x0fWorkloadRestore\x12\x1e.stormd.WorkloadRestoreRequest\x1a\x1f.stormd.WorkloadRestoreResponse\x12@\n" +
	"\tVmMigrate\x12\x18.stormd.VmMigrateRequest\x1a\x19.stormd.VmMigrateResponse\x12C\n" +
	"\n" +
	"VmSnapshot\x12\x19.stormd.VmSnapshotRequest\x1a\x1a.stormd.VmSnapshotResponseB:Z8github.com/glennswest/mkube/pkg/stormbase/proto;stormdpbb\x06proto3"

var (
	file_stormd_proto_rawDescOnce sync.Once
	file_stormd_proto_rawDescData []byte
)

func file_stormd_proto_rawDescGZIP() []byte {
	file_stormd_proto_rawDescOnce.Do(func() {
		file_stormd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stormd_proto_rawDesc), len(file_stormd_proto_rawDesc)))
	})
	return file_stormd_proto_rawDescData
}

var file_stormd_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_stormd_proto_goTypes = []any{
	(*WorkloadListRequest)(nil),         // 0: stormd.WorkloadListRequest
	(*WorkloadListResponse)(nil),        // 1: stormd.WorkloadListResponse
	(*WorkloadInfo)(nil),                // 2: stormd.WorkloadInfo
	(*WorkloadActionRequest)(nil),       // 3: stormd.WorkloadActionRequest
	(*WorkloadActionResponse)(nil),      // 4: stormd.WorkloadActionResponse
	(*WorkloadCreateRequest)(nil),       // 5: stormd.WorkloadCreateRequest
	(*PortMapping)(nil),                 // 6: stormd.PortMapping
	(*VolumeMount)(nil),                 // 7: stormd.VolumeMount
	(*WorkloadLogsRequest)(nil),         // 8: stormd.WorkloadLogsRequest
	(*LogEntry)(nil),                    // 9: stormd.LogEntry
	(*NodeStatusRequest)(nil),           // 10: stormd.NodeStatusRequest
	(*NodeStatusResponse)(nil),          // 11: stormd.NodeStatusResponse
	(*ImagePullRequest)(nil),            // 12: stormd.ImagePullRequest
	(*ImagePullResponse)(nil),           // 13: stormd.ImagePullResponse
	(*ImageListRequest)(nil),            // 14: stormd.ImageListRequest
	(*ImageListResponse)(nil),           // 15: stormd.ImageListResponse
	(*ImageEnsureRequest)(nil),          // 16: stormd.ImageEnsureRequest
	(*ImageEnsureResponse)(nil),         // 17: stormd.ImageEnsureResponse
	(*NodeDrainRequest)(nil),            // 18: stormd.NodeDrainRequest
	(*NodeDrainResponse)(nil),           // 19: stormd.NodeDrainResponse
	(*NodeCordonRequest)(nil),           // 20: stormd.NodeCordonRequest
	(*NodeCordonResponse)(nil),          // 21: stormd.NodeCordonResponse
	(*MeshUpdateRequest)(nil),           // 22: stormd.MeshUpdateRequest
	(*MeshNode)(nil),                    // 23: stormd.MeshNode
	(*MeshUpdateResponse)(nil),          // 24: stormd.MeshUpdateResponse
	(*ServiceUpdateRequest)(nil),        // 25: stormd.ServiceUpdateRequest
	(*ServiceEntry)(nil),                // 26: stormd.ServiceEntry
	(*ServiceEndpointMsg)(nil),          // 27: stormd.ServiceEndpointMsg
	(*ServiceUpdateResponse)(nil),       // 28: stormd.ServiceUpdateResponse
	(*ClusterStatusRequest)(nil),        // 29: stormd.ClusterStatusRequest
	(*ClusterStatusResponse)(nil),       // 30: stormd.ClusterStatusResponse
	(*WorkloadCheckpointRequest)(nil),   // 31: stormd.WorkloadCheckpointRequest
	(*WorkloadCheckpointResponse)(nil),  // 32: stormd.WorkloadCheckpointResponse
	(*WorkloadRestoreRequest)(nil),      // 33: stormd.WorkloadRestoreRequest
	(*WorkloadRestoreResponse)(nil),     // 34: stormd.WorkloadRestoreResponse
	(*VmMigrateRequest)(nil),            // 35: stormd.VmMigrateRequest
	(*VmMigrateResponse)(nil),           // 36: stormd.VmMigrateResponse
	(*VmSnapshotRequest)(nil),           // 37: stormd.VmSnapshotRequest
	(*VmSnapshotResponse)(nil),          // 38: stormd.VmSnapshotResponse
	(*NetworkPolicy)(nil),               // 39: stormd.NetworkPolicy
	(*NetworkPolicyRule)(nil),           // 40: stormd.NetworkPolicyRule
	(*NetworkPolicyApplyRequest)(nil),   // 41: stormd.NetworkPolicyApplyRequest
	(*NetworkPolicyApplyResponse)(nil),  // 42: stormd.NetworkPolicyApplyResponse
	(*NetworkPolicyDeleteRequest)(nil),  // 43: stormd.NetworkPolicyDeleteRequest
	(*NetworkPolicyDeleteResponse)(nil), // 44: stormd.NetworkPolicyDeleteResponse
	(*NetworkPolicyListRequest)(nil),    // 45: stormd.NetworkPolicyListRequest
	(*NetworkPolicyListResponse)(nil),   // 46: stormd.NetworkPolicyListResponse
}
var file_stormd_proto_depIdxs = []int32{
	2,  // 0: stormd.WorkloadListResponse.workloads:type_name -> stormd.WorkloadInfo
	6,  // 1: stormd.WorkloadCreateRequest.ports:type_name -> stormd.PortMapping
	7,  // 2: stormd.WorkloadCreateRequest.volumes:type_name -> stormd.VolumeMount
	23, // 3: stormd.MeshUpdateRequest.nodes:type_name -> stormd.MeshNode
	26, // 4: stormd.ServiceUpdateRequest.services:type_name -> stormd.ServiceEntry
	27, // 5: stormd.ServiceEntry.endpoints:type_name -> stormd.ServiceEndpointMsg
	23, // 6: stormd.ClusterStatusResponse.nodes:type_name -> stormd.MeshNode
	40, // 7: stormd.NetworkPolicy.ingress_rules:type_name -> stormd.NetworkPolicyRule
	40, // 8: stormd.NetworkPolicy.egress_rules:type_name -> stormd.NetworkPolicyRule
	39, // 9: stormd.NetworkPolicyApplyRequest.policy:type_name -> stormd.NetworkPolicy
	39, // 10: stormd.NetworkPolicyListResponse.policies:type_name -> stormd.NetworkPolicy
	0,  // 11: stormd.StormDaemon.WorkloadList:input_type -> stormd.WorkloadListRequest
	3,  // 12: stormd.StormDaemon.WorkloadStart:input_type -> stormd.WorkloadActionRequest
	3,  // 13: stormd.StormDaemon.WorkloadStop:input_type -> stormd.WorkloadActionRequest
	3,  // 14: stormd.StormDaemon.WorkloadRemove:input_type -> stormd.WorkloadActionRequest
	8,  // 15: stormd.StormDaemon.WorkloadLogs:input_type -> stormd.WorkloadLogsRequest
	10, // 16: stormd.StormDaemon.NodeStatus:input_type -> stormd.NodeStatusRequest
	12, // 17: stormd.StormDaemon.ImagePull:input_type -> stormd.ImagePullRequest
	14, // 18: stormd.StormDaemon.ImageList:input_type -> stormd.ImageListRequest
	5,  // 19: stormd.StormDaemon.WorkloadCreate:input_type -> stormd.WorkloadCreateRequest
	18, // 20: stormd.StormDaemon.NodeDrain:input_type -> stormd.NodeDrainRequest
	20, // 21: stormd.StormDaemon.NodeCordon:input_type -> stormd.NodeCordonRequest
	20, // 22: stormd.StormDaemon.NodeUncordon:input_type -> stormd.NodeCordonRequest
	16, // 23: stormd.StormDaemon.ImageEnsure:input_type -> stormd.ImageEnsureRequest
	22, // 24: stormd.StormDaemon.MeshUpdate:input_type -> stormd.MeshUpdateRequest
	25, // 25: stormd.StormDaemon.ServiceUpdate:input_type -> stormd.ServiceUpdateRequest
	29, // 26: stormd.StormDaemon.ClusterStatus:input_type -> stormd.ClusterStatusRequest
	41, // 27: stormd.StormDaemon.NetworkPolicyApply:input_type -> stormd.NetworkPolicyApplyRequest
	43, // 28: stormd.StormDaemon.NetworkPolicyDelete:input_type -> stormd.NetworkPolicyDeleteRequest
	45, // 29: stormd.StormDaemon.NetworkPolicyList:input_type -> stormd.NetworkPolicyListRequest
	31, // 30: stormd.StormDaemon.WorkloadCheckpoint:input_type -> stormd.WorkloadCheckpointRequest
	33, // 31: stormd.StormDaemon.WorkloadRestore:input_type -> stormd.WorkloadRestoreRequest
	35, // 32: stormd.StormDaemon.VmMigrate:input_type -> stormd.VmMigrateRequest
	37, // 33: stormd.StormDaemon.VmSnapshot:input_type -> stormd.VmSnapshotRequest
	1,  // 34: stormd.StormDaemon.WorkloadList:output_type -> stormd.WorkloadListResponse
	4,  // 35: stormd.StormDaemon.WorkloadStart:output_type -> stormd.WorkloadActionResponse
	4,  // 36: stormd.StormDaemon.WorkloadStop:output_type -> stormd.WorkloadActionResponse
	4,  // 37: stormd.StormDaemon.WorkloadRemove:output_type -> stormd.WorkloadActionResponse
	9,  // 38: stormd.StormDaemon.WorkloadLogs:output_type -> stormd.LogEntry
	11, // 39: stormd.StormDaemon.NodeStatus:output_type -> stormd.NodeStatusResponse
	13, // 40: stormd.StormDaemon.ImagePull:output_type -> stormd.ImagePullResponse
	15, // 41: stormd.StormDaemon.ImageList:output_type -> stormd.ImageListResponse
	4,  // 42: stormd.StormDaemon.WorkloadCreate:output_type -> stormd.WorkloadActionResponse
	19, // 43: stormd.StormDaemon.NodeDrain:output_type -> stormd.NodeDrainResponse
	21, // 44: stormd.StormDaemon.NodeCordon:output_type -> stormd.NodeCordonResponse
	21, // 45: stormd.StormDaemon.NodeUncordon:output_type -> stormd.NodeCordonResponse
	17, // 46: stormd.StormDaemon.ImageEnsure:output_type -> stormd.ImageEnsureResponse
	24, // 47: stormd.StormDaemon.MeshUpdate:output_type -> stormd.MeshUpdateResponse
	28, // 48: stormd.StormDaemon.ServiceUpdate:output_type -> stormd.ServiceUpdateResponse
	30, // 49: stormd.StormDaemon.ClusterStatus:output_type -> stormd.ClusterStatusResponse
	42, // 50: stormd.StormDaemon.NetworkPolicyApply:output_type -> stormd.NetworkPolicyApplyResponse
	44, // 51: stormd.StormDaemon.NetworkPolicyDelete:output_type -> stormd.NetworkPolicyDeleteResponse
	46, // 52: stormd.StormDaemon.NetworkPolicyList:output_type -> stormd.NetworkPolicyListResponse
	32, // 53: stormd.StormDaemon.WorkloadCheckpoint:output_type -> stormd.WorkloadCheckpointResponse
	34, // 54: stormd.StormDaemon.WorkloadRestore:output_type -> stormd.WorkloadRestoreResponse
	36, // 55: stormd.StormDaemon.VmMigrate:output_type -> stormd.VmMigrateResponse
	38, // 56: stormd.StormDaemon.VmSnapshot:output_type -> stormd.VmSnapshotResponse
	34, // [34:57] is the sub-list for method output_type
	11, // [11:34] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_stormd_proto_init() }
func file_stormd_proto_init() {
	if File_stormd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stormd_proto_rawDesc), len(file_stormd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stormd_proto_goTypes,
		DependencyIndexes: file_stormd_proto_depIdxs,
		MessageInfos:      file_stormd_proto_msgTypes,
	}.Build()
	File_stormd_proto = out.File
	file_stormd_proto_goTypes = nil
	file_stormd_proto_depIdxs = nil
}
